### ISSUE TITLE
error Cannot GET /

### ISSUE THREAD

**Issue by eki01** [muriloe/Hauora#2]
how to fix error "Cannot GET /" i am access in browser http://localhost:3000/
thank's

**Comment by muriloe** [comment]
http://localhost:3000/ is default port to back-end project.
"Cannot GET /" is not error because i didnt insert any response to this route.

To run the project first run back-end project running **node app.js** .
And then run frontend project **ng s** .

The front-end will running in http://localhost:4200/

**Comment by eki01** [comment]
ok solved
thanks
